[package]
name = "brian-rs-macros"
version = "0.1.0"
authors = ["Heman Gandhi <hemangandhi@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
dimensioned = "0.7.0"
proc-macro2 = "1.0.24"
quote = "1.0"
syn = { version = "1.0.62", features = ["full"] }